### ISSUE TITLE
Already patched?

### ISSUE THREAD

**Issue by wiesner-philipp** [sirmordred/AngelaRoot#2]
C:\adb>adb shell sh /storage/emulated/0/Android/data/com.mordred.angelaroot/files/angelaroot_starter_step2.sh
info: angelaroot_starter.sh STEP2 begin
cp: bad '/data/user/0/com.mordred.angelaroot/files/su': Permission denied
info: su binary copied
cp: bad '/data/user/0/com.mordred.angelaroot/files/Superuser.apk': Permission denied
info: Superuser app copied
chmod: /data/local/tmp/su: No such file or directory
chmod: /data/local/tmp/Superuser.apk: No such file or directory
setenforce: Couldn't set enforcing status to '0': Permission denied
info: Selinux disabled
mount: bad /etc/fstab: No such file or directory
info: su binary mounted
info: setting permissions of su binary...
chmod: /system/xbin/su: No such file or directory
info: launching su...
/storage/emulated/0/Android/data/com.mordred.angelaroot/files/angelaroot_starter_step2.sh[18]: su: not found
Error: Can't open non-file: /data/local/tmp/Superuser.apk
info: Superuser.apk installed succesfully
setprop: failed to set property 'persist.sys.adbroot' to '0'
YOUR DEVICE IS NOW ROOTED !!! WELCOME TO FSOCIETY

Currently running the latest OTA on a OnePlus 3.

**Comment by wiesner-philipp** [comment]
Maybe this helps for debugging :)
adb root
adbd cannot run as root in production builds

**Comment by sirmordred** [comment]
can you type the  "adb shell pm list packages" and look for "com.android.engineermode" if its not in the list then yeah we can clearly say that the Oneplus patched the vulnerability with latest OTA

**Comment by wiesner-philipp** [comment]
I have it in the list, its still there, I even ran "adb shell am start -n com.android.engineeringmode/.qualcomm.DiagEnabled --es "code" "angela"" and the engineer mode window pops up letting me toggle some settings.
However if I run "adb root" the message "adbd cannot run as root in production builds" comes up.

**Comment by sirmordred** [comment]
type the followings:
adb shell am start -n com.android.engineeringmode/.qualcomm.DiagEnabled --es "code" "angela"
adb shell id

and write the output here

**Comment by wiesner-philipp** [comment]
Sure! :)
C:\adb>adb shell am start -n com.android.engineeringmode/.qualcomm.DiagEnabled --es "code" "angela"
Starting: Intent { cmp=com.android.engineeringmode/.qualcomm.DiagEnabled (has extras) }

C:\adb>adb shell id
uid=2000(shell) gid=2000(shell) groups=2000(shell),1004(input),1007(log),1011(adb),1015(sdcard_rw),1028(sdcard_r),3001(net_bt_admin),3002(net_bt),3003(inet),3006(net_bw_stats),3009(readproc) context=u:r:shell:s0

**Comment by sirmordred** [comment]
Yeah, logs clearly state that they patched the vulnerability on latest OTA for Oneplus 3

**Comment by sirmordred** [comment]
Can you also extract that EngineerMode.apk?

adb shell pm path com.android.engineermode (you will get the path something like :/system/priv-apps/EngineerMode.apk )

and type the
adb pull PATH_YOU_GET_FROM_PREVIOUS_STEP C:\

it will pull/extract the apk and save it to C drive (i assume you are using windows)
and then upload it somewhere on the net(mediafire maybe)
send the link

Thanx

**Comment by wiesner-philipp** [comment]
Alright! Here it is: https://www.file-upload.net/download-12829121/EngineeringMode.apk.html
Hope u'll get some info out of it :)

**Comment by sirmordred** [comment]
Thanx so much
