### ISSUE TITLE
error when using angela root

### ISSUE THREAD

**Issue by pranabjoshi** [sirmordred/AngelaRoot#3]
I got the following error while using angelaroot. please find the log below:

C:\Users\USER\ADT\adt-bundle-windows-x86_64-20140702\sdk\platform-tools>adb devi
ces
List of devices attached
aa2f851 device

C:\Users\USER\ADT\adt-bundle-windows-x86_64-20140702\sdk\platform-tools>adb shel
l sh /storage/emulated0/Android?data/com.mordred.angelaroot/files/angelaroot_sta
rter_step1.sh
sh: /storage/emulated0/Android?data/com.mordred.angelaroot/files/angelaroot_star
ter_step1.sh: No such file or directory

C:\Users\USER\ADT\adt-bundle-windows-x86_64-20140702\sdk\platform-tools>adb shel
l sh /storage/emulated/0/Android/data/com.mordred.angelaroot/files/angelaroot_st
arter_step1.sh
info: angelaroot_starter.sh STEP1 begin
Starting: Intent { cmp=com.android.engineeringmode/.qualcomm.DiagEnabled (has ex
tras) }
Ok, STEP1 is completed, let's do STEP2

C:\Users\USER\ADT\adt-bundle-windows-x86_64-20140702\sdk\platform-tools>adb shel
l sh /storage/emulated/0/Android/data/com.mordred.angelaroot/files/angelaroot_st
arter_step2.sh
info: angelaroot_starter.sh STEP2 begin
cp: bad '/data/user/0/com.mordred.angelaroot/files/su': Permission denied
info: su binary copied
cp: bad '/data/user/0/com.mordred.angelaroot/files/Superuser.apk': Permission de
nied
info: Superuser app copied
chmod: /data/local/tmp/su: No such file or directory
chmod: /data/local/tmp/Superuser.apk: No such file or directory
setenforce: Couldn't set enforcing status to '0': Permission denied
info: Selinux disabled
mount: bad /etc/fstab: No such file or directory
info: su binary mounted
info: setting permissions of su binary...
chmod: /system/xbin/su: No such file or directory
info: launching su...
/storage/emulated/0/Android/data/com.mordred.angelaroot/files/angelaroot_starter
_step2.sh[18]: su: not found
Error: Can't open non-file: /data/local/tmp/Superuser.apk
info: Superuser.apk installed succesfully
setprop: failed to set property 'persist.sys.adbroot' to '0'
YOUR DEVICE IS NOW ROOTED !!! WELCOME TO FSOCIETY

C:\Users\USER\ADT\adt-bundle-windows-x86_64-20140702\sdk\platform-tools>

**Comment by mike9421** [comment]
me too

**Comment by sirmordred** [comment]
hi

it seems the vulnerability in your roms are already patched by Oneplus OTAs so its normal that you guys are getting these types of errors
